[package]
name = "aoc-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
binary-tree = "0.2.0"
itertools = "0.13.0"
nalgebra = "0.33.2"
nom = "7.1.3"
partial_sort = "0.2.0"
regex = "1.11.1"
